[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplot>=0.1.9",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "reportlab>=4.5.1",
    "requests>=2.34.2",
]

[tool.uv.workspace]
members = [
    "123",
    "0516",
    "0523",
    "0530",
    "0627",
]
